#              ____             __ _ _
#   __ _  ___ |  _ \ _ __ ___  / _(_) | ___
#  / _` |/ _ \| |_) | '__/ _ \| |_| | |/ _ \
# | (_| | (_) |  __/| | | (_) |  _| | |  __/
#  \__, |\___/|_|   |_|  \___/|_| |_|_|\___|
#  |___/


language: "ru_ru"

default_title: "&eПрофиль %player_name%"

gui:
  size: 54
  items:
    1:
      material: PLAYER_HEAD
      head_owner: "%player_name%"
      display_name: "%player_name%"
      lore:
        - "&#E2ADFDВремя игры: &f%cmi_user_playtime_hoursf% &7час."
        - "&#ACD45BРанг: &7%luckperms_prefix%"
        - "&#ACD45BНик: &7%flectonepulse_player%"
      update: true
    2:
      material: DIAMOND_PICKAXE
      display_name: "&5Добыча"
      lore:
        - "&7Блоков добыто: %statistic_mine_block%"
      update: true
    3:
      material: STONE
      display_name: "&eИнфа"
      lore:
        - "&7Здоровье: &c%player_health%"
        - "&aЛайки: &f%profile_like%"
        - "&cДизлайки: &f%profile_dislike%"
        - "&eСтатус: &f%profile_status%"
      update: true
    4:
      material: EMERALD
      display_name: "&aПоставить лайк"
      lore:
        - "&7Нажмите, чтобы поставить лайк!"
      command: "[player] goprofile like {player}"  # Обновлено
      cooldown: 5
      sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
      update: false
    5:
      material: REDSTONE
      display_name: "&cПоставить дизлайк"
      lore:
        - "&7Нажмите, чтобы поставить дизлайк!"
      command: "[player] goprofile dislike {player}"  # Обновлено
      cooldown: 5
      sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
      update: false
    6:
      material: EMERALD_BLOCK
      display_name: "&aУбрать лайк"
      lore:
        - "&7Нажмите, чтобы убрать свой лайк!"
      command: "[player] goprofile unlike {player}"  # Обновлено
      cooldown: 5
      sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
      update: false
    7:
      material: REDSTONE_BLOCK
      display_name: "&cУбрать дизлайк"
      lore:
        - "&7Нажмите, чтобы убрать свой дизлайк!"
      command: "[player] goprofile undislike {player}"  # Обновлено
      cooldown: 5
      sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
      update: false
    53:
      material: ARROW
      display_name: "&eОткрыть меню"
      lore:
        - "&7Нажмите, чтобы открыть меню!"
      command: "[console] dm open menu {player}"
      cooldown: 5
      sound: "ENTITY_ITEM_PICKUP"
      update: false
    52:
      material: BARRIER
      display_name: "&cЗакрыть"
      lore:
        - "&7Нажмите, чтобы закрыть профиль!"
      close: true
      sound: "BLOCK_NOTE_BLOCK_PLING"
      update: false

  player_items:
    helmet: 10
    chestplate: 11
    leggings: 12
    boots: 13
    main_hand: 19
    off_hand: 20