#              ____             __ _ _
#   __ _  ___ |  _ \ _ __ ___  / _(_) | ___
#  / _` |/ _ \| |_) | '__/ _ \| |_| | |/ _ \
# | (_| | (_) |  __/| | | (_) |  _| | |  __/
#  \__, |\___/|_|   |_|  \___/|_| |_|_|\___|
#  |___/

language: "ru_ru"
version-check: true

default_title: "<yellow>Профиль игрока <player_name>"

gui:
  size: 54
  items:
    0-53:
      material: BLACK_STAINED_GLASS_PANE
      display_name: " "
      update: false

    13:
      material: PLAYER_HEAD
      head_owner: "%player_name%"
      display_name: "<player_name>"
      lore:
        - "<gradient:#E2ADFD:#FFFFFF>Время игры: <white>%cmi_user_playtime_hoursf% <gray>часов"
        - "<gradient:#ACD45B:#FFFFFF>Ранг: <gray>%luckperms_prefix%"
      update: true
    23:
      material: REDSTONE
      display_name: "<red>Дизлайк"
      lore:
        - "<gray>Нажмите, чтобы поставить дизлайк!"
      command: "[player] goprofile dislike {player}"
      cooldown: 5
      sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
      update: false
    22:
      material: STONE
      display_name: "<yellow>Информация"
      lore:
        - "<gray>Здоровье: <red>%player_health%"
        - "<green>Лайки: <white>%profile_like%"
        - "<red>Дизлайки: <white>%profile_dislike%"
        - "<yellow>Статус: <white>%profile_status%"
        - "<gray>Блоков добыто: %statistic_mine_block%"
      update: true
    21:
      material: EMERALD
      display_name: "<green>Лайк"
      lore:
        - "<gray>Нажмите, чтобы поставить лайк!"
      command: "[player] goprofile like {player}"
      cooldown: 5
      sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
      update: false
    30:
      material: EMERALD_BLOCK
      display_name: "<green>Убрать лайк"
      lore:
        - "<gray>Нажмите, чтобы убрать ваш лайк!"
      command: "[player] goprofile unlike {player}"
      cooldown: 5
      sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
      update: false
    32:
      material: REDSTONE_BLOCK
      display_name: "<red>Убрать дизлайк"
      lore:
        - "<gray>Нажмите, чтобы убрать ваш дизлайк!"
      command: "[player] goprofile undislike {player}"
      cooldown: 5
      sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
      update: false

    45:
      material: ARROW
      display_name: "<yellow>Открыть меню"
      lore:
        - "<gray>Нажмите, чтобы открыть меню!"
      command: "[console] dm open menu {player}"
      cooldown: 5
      sound: "ENTITY_ITEM_PICKUP"
      update: false
    53:
      material: BARRIER
      display_name: "<red>Закрыть"
      lore:
        - "<gray>Нажмите, чтобы закрыть профиль!"
      close: true
      sound: "BLOCK_NOTE_BLOCK_PLING"
      update: false

  player_items:
    helmet: 1
    chestplate: 10
    leggings: 19
    boots: 28
    main_hand: 3
    off_hand: 5