#              ____             __ _ _
#   __ _  ___ |  _ \ _ __ ___  / _(_) | ___
#  / _` |/ _ \| |_) | '__/ _ \| |_| | |/ _ \
# | (_| | (_) |  __/| | | (_) |  _| | |  __/
#  \__, |\___/|_|   |_|  \___/|_| |_|_|\___|
#  |___/

language: "ru_ru"
version-check: true

default_title: "&eProfile of %player_name%"

gui:
  size: 54
  items:
    0-53:
      material: BLACK_STAINED_GLASS_PANE
      display_name: " "
      update: false

    13:
      material: PLAYER_HEAD
      head_owner: "%player_name%"
      display_name: "%player_name%"
      lore:
        - "&#E2ADFDPlaytime: &f%cmi_user_playtime_hoursf% &7hours"
        - "&#ACD45BRank: &7%luckperms_prefix%"
        - "&#ACD45BNickname: &7%flectonepulse_player%"
      update: true
    23:
      material: REDSTONE
      display_name: "&cDislike"
      lore:
        - "&7Click to dislike!"
      command: "[player] goprofile dislike {player}"
      cooldown: 5
      sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
      update: false
    22:
      material: STONE
      display_name: "&eInfo"
      lore:
        - "&7Health: &c%player_health%"
        - "&aLikes: &f%profile_like%"
        - "&cDislikes: &f%profile_dislike%"
        - "&eStatus: &f%profile_status%"
        - "&7Blocks Mined: %statistic_mine_block%"
      update: true
    21:
      material: EMERALD
      display_name: "&aLike"
      lore:
        - "&7Click to like!"
      command: "[player] goprofile like {player}"
      cooldown: 5
      sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
      update: false
    30:
      material: EMERALD_BLOCK
      display_name: "&aRemove Like"
      lore:
        - "&7Click to remove your like!"
      command: "[player] goprofile unlike {player}"
      cooldown: 5
      sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
      update: false
    32:
      material: REDSTONE_BLOCK
      display_name: "&cRemove Dislike"
      lore:
        - "&7Click to remove your dislike!"
      command: "[player] goprofile undislike {player}"
      cooldown: 5
      sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
      update: false

    45:
      material: ARROW
      display_name: "&eOpen Menu"
      lore:
        - "&7Click to open the menu!"
      command: "[console] dm open menu {player}"
      cooldown: 5
      sound: "ENTITY_ITEM_PICKUP"
      update: false
    53:
      material: BARRIER
      display_name: "&cClose"
      lore:
        - "&7Click to close the profile!"
      close: true
      sound: "BLOCK_NOTE_BLOCK_PLING"
      update: false

  player_items:
    helmet: 1
    chestplate: 10
    leggings: 19
    boots: 28
    main_hand: 3
    off_hand: 5