name: goProfile
version: 1.3
main: org.tamraz.goprofile.GoProfile
api-version: 1.20
softdepend: [PlaceholderAPI]

commands:
  goprofile:
    description: Main command for goProfile
    usage: /<command> <subcommand>
    aliases: []
    permission: goprofile.use

permissions:
  goprofile.use:
    description: Allows usage of goprofile commands
    default: true
  profileplugin.admin:
    description: Access to admin commands of the plugin
    default: op
