name: goProfile
version: 1.0
main: org.tamraz.goprofile.GoProfile
api-version: 1.21
softdepend: [PlaceholderAPI]
commands:
  goprofile:
    description: Main command for goprofile
    usage: /<command> <subcommand>
    aliases: []
    permission: goprofile.use
permissions:
  goprofile.use:
    description: Allows usage of goprofile commands
    default: true
  goprofile.admin:
    description: Access to admin commands of the plugin
    default: op